#WORDS FOR HANGMAN GAME

words = ("apple","banana","orange","grape","mango","peach","pear","melon","berry","plum",
"house","chair","table","lamp","sofa","shelf","door","window","floor","wall",
"happy","smile","laugh","joy","love","kind","gentle","soft","warm","hug",
"cat","dog","fish","bird","mouse","horse","sheep","goat","cow","duck",
"sun","moon","star","cloud","rain","wind","snow","storm","fog","sky",
"car","bus","train","bike","truck","plane","boat","ship","wheel","road",
"red","blue","green","yellow","white","black","pink","purple","brown","gray",
"book","pen","paper","pencil","ruler","bag","eraser","marker","notebook","folder",
"hot","cold","warm","cool","dry","wet","fast","slow","big","small",
"tree","plant","flower","grass","leaf","root","branch","wood","bark","seed",
"ball","game","play","run","jump","walk","dance","sing","clap","kick",
"water","milk","juice","tea","coffee","soda","soup","sugar","salt","butter",
"shirt","pants","shoes","hat","dress","coat","scarf","glove","sock","belt",
"bread","cheese","fruit","meat","pizza","pasta","rice","salad","cake","cookie",
"school","teacher","student","class","lesson","test","homework","subject","exam","grade",
"clock","watch","time","alarm","minute","hour","second","day","week","month",
"music","song","sound","drum","guitar","piano","violin","flute","trumpet","singer",
"friend","family","brother","sister","mother","father","aunt","uncle","cousin","baby",
"light","dark","bright","dim","shade","shadow","color","paint","draw","picture",
"street","city","village","town","park","garden","bridge","river","beach","ocean",
"phone","laptop","computer","tablet","screen","keyboard","mouse","charger","camera","radio",
"morning","noon","afternoon","evening","night","sunrise","sunset","midnight","today","tomorrow",
"fun","joke","laugh","smile","happy","silly","crazy","weird","cool","nice",
"egg","butter","jam","toast","honey","syrup","cereal","snack","biscuit","chocolate",
"doctor","nurse","hospital","medicine","health","clinic","patient","cure","injury","fever",
"mountain","hill","valley","river","lake","forest","desert","island","cave","field",
"money","coin","cash","bank","wallet","credit","debit","price","cost","cheap",
"tall","short","long","wide","narrow","deep","shallow","round","flat","thick",
"fast","slow","quick","lazy","heavy","light","strong","weak","soft","hard",
"food","drink","meal","snack","breakfast","lunch","dinner","hungry","thirsty","full",
"open","close","lock","key","handle","knob","door","gate","window","curtain",
"cold","hot","warm","cool","freeze","melt","burn","boil","steam","chill")